<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:FileDescriptionType xmlns:ns2="http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType" xmlns:ns3="http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType">
    <FileIdentifier>MLMSSHOPXML20160725153000</FileIdentifier>
    <FileDateTime>2016/07/25 15:30:00</FileDateTime>
    <FileRecordCount>10</FileRecordCount>
    <FileTypeInfo FileType="DailyIncremental"/>
    <IncrementalRecord>
        <UserInfo UserID="AB_DEV_1A" FirstName="AB" ActiveStatus="active" LastName="Testing" npn="1122"/>
        <AddressInfo StreetAddress="1800 Ridge" ZipCode="60201" EmailAddress="mphoff@us.ibm.com" PhoneNumber="5555555555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Evanston</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>08:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>31/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT1TEST0" FirstName="anton" ActiveStatus="active" LastName="weiss" npn="12341234"/>
        <AddressInfo StreetAddress="2515 AVALON PL" ZipCode="20783" EmailAddress="Agent1Test0@yopmail.com" PhoneNumber="3014345710">
            <ns2:State>MD</ns2:State>
            <ns2:City>HYATTSVILLE</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Agency Name</ns2:AgencyName>
                <ns2:AgencyUrl>Agency URL</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>16/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT2TEST0" FirstName="John" ActiveStatus="active" LastName="Carson" npn="1231234"/>
        <AddressInfo StreetAddress="106 greenfield rd" ZipCode="22554" EmailAddress="agent2test0@yopmail.com" PhoneNumber="3334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Stafford</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>23/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>14/09/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT3TEST0" FirstName="Patrick" ActiveStatus="active" LastName="Barnes" npn="333"/>
        <AddressInfo StreetAddress="Street" ZipCode="22554" EmailAddress="Agent2Test0@yopmail.com" PhoneNumber="3333333333">
            <ns2:State>VA</ns2:State>
            <ns2:City>city</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>23/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT4TEST0" FirstName="Mattie" ActiveStatus="active" LastName="Boyd" npn="4893742890"/>
        <AddressInfo StreetAddress="29 High Noon Trail" ZipCode="80477" EmailAddress="testagent5@yopmail.com" PhoneNumber="3334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Steamboat Springs</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="DEVUSER1" FirstName="DEV" ActiveStatus="active" LastName="User" npn="1122"/>
        <AddressInfo StreetAddress="1800 DevUserOne Lane" ZipCode="60201" EmailAddress="mphoff@us.ibm.com" PhoneNumber="7735787742">
            <ns2:State>CO</ns2:State>
            <ns2:City>DevUserOne City</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>08:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>27/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="INC5MLMSNEWAGENT" FirstName="ANTON" ActiveStatus="active" LastName="WEISS" npn="1234567890"/>
        <AddressInfo StreetAddress="1 Business Street Address" ZipCode="20151" EmailAddress="BUSINESSEMAIL@YOPMAIL.COM" PhoneNumber="1234567890">
            <ns2:State>VA</ns2:State>
            <ns2:City>Business City</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>available</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>Spanish</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Mailing address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>22/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMS@T0-06" FirstName="fname" ActiveStatus="active" LastName="lname" npn="122"/>
        <AddressInfo StreetAddress="1900 Ridge" ZipCode="55555" EmailAddress="mphoff@us.ibm.com" PhoneNumber="7777777777">
            <ns2:State>CO</ns2:State>
            <ns2:City>Yahoo</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>08:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>available</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>03/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="SJMEYER" FirstName="fname" ActiveStatus="active" LastName="lname" npn="12"/>
        <AddressInfo StreetAddress="addd" ZipCode="12312" EmailAddress="test@gmail.com" PhoneNumber="1231231231">
            <ns2:State>CO</ns2:State>
            <ns2:City>cc</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>08:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>15/04/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="VCIMPL@045" FirstName="VC-IMPL" ActiveStatus="active" LastName="O'Fortyfive" npn="1234567889"/>
        <AddressInfo StreetAddress="12" ZipCode="21044" EmailAddress="vcollin@qssinc.com" PhoneNumber="4105551212">
            <ns2:State>CO</ns2:State>
            <ns2:City>Columbia</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>08:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>02/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
</ns3:FileDescriptionType>
