<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:FileDescriptionType xmlns:ns2="http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType" xmlns:ns3="http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType">
    <FileIdentifier>MLMSSHOPXML20160727215500</FileIdentifier>
    <FileDateTime>2016/07/27 21:55:00</FileDateTime>
    <FileRecordCount>0</FileRecordCount>
    <FileTypeInfo FileType="DailyIncremental"/>
</ns3:FileDescriptionType>
