<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:FileDescriptionType xmlns:ns2="http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType" xmlns:ns3="http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType">
    <FileIdentifier>MLMSSHOPXML20160722104000</FileIdentifier>
    <FileDateTime>2016/07/22 10:40:00</FileDateTime>
    <FileRecordCount>5</FileRecordCount>
    <FileTypeInfo FileType="DailyIncremental"/>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT2" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt2" npn="0123456788"/>
        <AddressInfo StreetAddress="134 Some St" ZipCode="20194" EmailAddress="anu@us.ibm.com" PhoneNumber="7037420501">
            <ns2:State>VA</ns2:State>
            <ns2:City>Reston</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>ibm</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="INC5NEWAGENT" FirstName="ANTON" ActiveStatus="active" LastName="WEISS" npn="0000022554"/>
        <AddressInfo StreetAddress="1 BUSINESS STREET ADDRESS" ZipCode="22554" EmailAddress="INC5NEWAGENTBUSINESS@YOPMAIL.COM" PhoneNumber="4103943208">
            <ns2:State>VA</ns2:State>
            <ns2:City>STAFFORD</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>INC5NEWAGENT</ns2:AgencyName>
                <ns2:AgencyUrl>WWW.INC5NEWAGENT.COM</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT1" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt1" npn="0123456789"/>
        <AddressInfo StreetAddress="123 Some St" ZipCode="20171" EmailAddress="anu@us.ibm.com" PhoneNumber="7037133333">
            <ns2:State>VA</ns2:State>
            <ns2:City>Herndon</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>IBM</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT3" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt3" npn="0123456787"/>
        <AddressInfo StreetAddress="154 Some St" ZipCode="20190" EmailAddress="anu@us.ibm.com" PhoneNumber="7037428757">
            <ns2:State>VA</ns2:State>
            <ns2:City>Ashburn</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>cnn</ns2:AgencyName>
                <ns2:AgencyUrl>www.cnn.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT4" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt4" npn="0123456786"/>
        <AddressInfo StreetAddress="167 Some St" ZipCode="20170" EmailAddress="anu@us.ibm.com" PhoneNumber="1234567890">
            <ns2:State>VA</ns2:State>
            <ns2:City>Herndon</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
</ns3:FileDescriptionType>
