<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:FileDescriptionType xmlns:ns2="http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType" xmlns:ns3="http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType">
    <FileIdentifier>MLMSSHOPXML20160722135500</FileIdentifier>
    <FileDateTime>2016/07/22 13:55:00</FileDateTime>
    <FileRecordCount>35</FileRecordCount>
    <FileTypeInfo FileType="MonthlyFull"/>
    <IncrementalRecord>
        <UserInfo UserID="AB_DEV_1A" FirstName="AB" ActiveStatus="active" LastName="Testing" npn="0000001122"/>
        <AddressInfo StreetAddress="1800 Ridge" ZipCode="60201" EmailAddress="mphoff@us.ibm.com" PhoneNumber="5555555555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Evanston</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>10:00 PM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>10:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>31/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AB_DEV_2JULA" FirstName="AB" ActiveStatus="active" LastName="Person" npn="0000001122"/>
        <AddressInfo StreetAddress="1800 Ridge" ZipCode="55555" EmailAddress="matthew.price.hoff@gmail.com" PhoneNumber="7777777777">
            <ns2:State>CO</ns2:State>
            <ns2:City>Ave</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>09:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>14/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AB_DEV_3" FirstName="MPhoff" ActiveStatus="active" LastName="stuff" npn="0000000221"/>
        <AddressInfo StreetAddress="122 Riverside Ave" ZipCode="55555" EmailAddress="hoffmatt22@yahoo.com" PhoneNumber="7777777777">
            <ns2:State>WA</ns2:State>
            <ns2:City>Marinette</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>09:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Mailing address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>FBI</ns2:AgencyName>
                <ns2:AgencyUrl>www.fbi.gov</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>16/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT0TEST0" FirstName="Marcia" ActiveStatus="active" LastName="Duncan" npn="0012341234"/>
        <AddressInfo StreetAddress="2515 AVALON PL" ZipCode="20783" EmailAddress="Agent0Test0@yopmail.com" PhoneNumber="3014345710">
            <ns2:State>MD</ns2:State>
            <ns2:City>HYATTSVILLE</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>16/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT1TEST0" FirstName="anton" ActiveStatus="active" LastName="weiss" npn="0012341234"/>
        <AddressInfo StreetAddress="2515 AVALON PL" ZipCode="20783" EmailAddress="Agent1Test0@yopmail.com" PhoneNumber="3014345710">
            <ns2:State>MD</ns2:State>
            <ns2:City>HYATTSVILLE</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>16/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT2TEST0" FirstName="John" ActiveStatus="active" LastName="Carson" npn="0001231234"/>
        <AddressInfo StreetAddress="106 greenfield rd" ZipCode="22554" EmailAddress="agent2test0@yopmail.com" PhoneNumber="3334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Stafford</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>23/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>14/09/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT3TEST0" FirstName="Patrick" ActiveStatus="active" LastName="Barnes" npn="0012312312"/>
        <AddressInfo StreetAddress="Street" ZipCode="22554" EmailAddress="Agent2Test0@yopmail.com" PhoneNumber="1231231234">
            <ns2:State>VA</ns2:State>
            <ns2:City>city</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>23/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT4TEST0" FirstName="agent4" ActiveStatus="active" LastName="test0" npn="4893742890"/>
        <AddressInfo StreetAddress="29 High Noon Trail" ZipCode="80477" EmailAddress="testagent5@yopmail.com" PhoneNumber="3334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Steamboat Springs</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT5TEST0" FirstName="Colinda" ActiveStatus="active" LastName="Piyapant" npn="4893742891"/>
        <AddressInfo StreetAddress="45 High Noon Trail" ZipCode="80477" EmailAddress="testagent0@yopmail.com" PhoneNumber="1334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Steamboat Springs</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="AGENT728" FirstName="agent" ActiveStatus="active" LastName="tse" npn="0000012345"/>
        <AddressInfo StreetAddress="100 main street" ZipCode="92311" EmailAddress="728a@g.com" PhoneNumber="9239999999">
            <ns2:State>CO</ns2:State>
            <ns2:City>bus city2</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>27/08/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="DEVUSER1" FirstName="DEV" ActiveStatus="active" LastName="User" npn="0000001122"/>
        <AddressInfo StreetAddress="1800 DevUserOne Lane" ZipCode="60201" EmailAddress="mphoff@us.ibm.com" PhoneNumber="7735787742">
            <ns2:State>CO</ns2:State>
            <ns2:City>DevUserOne City</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>10:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>27/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="HELPUSER8" FirstName="HDUEightyNine" ActiveStatus="active" LastName="last" npn="4657667123"/>
        <AddressInfo StreetAddress="srthyswrt" ZipCode="21433" EmailAddress="rguttikonda@qssinc.com" PhoneNumber="7657693212">
            <ns2:State>CO</ns2:State>
            <ns2:City>rstdrtyges</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>16/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="INC5NEWAGENT" FirstName="ANTON" ActiveStatus="active" LastName="WEISS" npn="0000022554"/>
        <AddressInfo StreetAddress="1 BUSINESS STREET ADDRESS" ZipCode="22554" EmailAddress="INC5NEWAGENTBUSINESS@YOPMAIL.COM" PhoneNumber="4103943208">
            <ns2:State>VA</ns2:State>
            <ns2:City>STAFFORD</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>INC5NEWAGENT</ns2:AgencyName>
                <ns2:AgencyUrl>WWW.INC5NEWAGENT.COM</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMS@T0-06" FirstName="fname" ActiveStatus="active" LastName="lname" npn="0000000122"/>
        <AddressInfo StreetAddress="1900 Ridge" ZipCode="55555" EmailAddress="mphoff@us.ibm.com" PhoneNumber="7777777777">
            <ns2:State>CO</ns2:State>
            <ns2:City>Yahoo</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>10:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>available</ns2:Saturday>
                <ns2:Sunday>available</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>03/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMS@T0-07" FirstName="fname" ActiveStatus="active" LastName="lname" npn="0000221333"/>
        <AddressInfo StreetAddress="1990 Lane" ZipCode="55555" EmailAddress="mphoff@us.ibm.com" PhoneNumber="8888888888">
            <ns2:State>CO</ns2:State>
            <ns2:City>Marinette</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>09:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>03/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMSTESTAGENT1" FirstName="mlms" ActiveStatus="active" LastName="test agent1" npn="4893742892"/>
        <AddressInfo StreetAddress="45 High Noon Trail" ZipCode="80477" EmailAddress="testagent0@yopmail.com" PhoneNumber="1334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Steamboat Springs</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMSTESTAGENT10" FirstName="Anton" ActiveStatus="active" LastName="Weiss" npn="0000034885"/>
        <AddressInfo StreetAddress="106 greenfield rd" ZipCode="22554" EmailAddress="mlmstestagent10@yopmail.com" PhoneNumber="3334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>stafford</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMSTESTAGENT4" FirstName="Anton" ActiveStatus="active" LastName="Weiss" npn="4893742893"/>
        <AddressInfo StreetAddress="45 High Noon Trail" ZipCode="80477" EmailAddress="testagent0@yopmail.com" PhoneNumber="1334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Steamboat Springs</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMSTESTAGENT5" FirstName="mlms" ActiveStatus="active" LastName="testagent5" npn="4893742894"/>
        <AddressInfo StreetAddress="45 High Noon Trail" ZipCode="80477" EmailAddress="testagent0@yopmail.com" PhoneNumber="1334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Steamboat Springs</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>14/09/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="MLMSTESTAGENT8" FirstName="Anton" ActiveStatus="active" LastName="Weiss" npn="4893742894"/>
        <AddressInfo StreetAddress="106 greenfield rd" ZipCode="22554" EmailAddress="mlmstestagent8@yopmail.com" PhoneNumber="3334445555">
            <ns2:State>CO</ns2:State>
            <ns2:City>Stafford</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>29/05/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="REL14TEST0-01" FirstName="BYRON" ActiveStatus="active" LastName="BATTEASE" npn="6546509871"/>
        <AddressInfo StreetAddress="esrgfes" ZipCode="21686" EmailAddress="rkumbum@qssinc.com" PhoneNumber="7659869704">
            <ns2:State>CO</ns2:State>
            <ns2:City>sdgserg</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>27/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="REL14TEST0-02" FirstName="BYRON" ActiveStatus="active" LastName="BATTEASE" npn="6783452344"/>
        <AddressInfo StreetAddress="asdf" ZipCode="34532" EmailAddress="rkumbum@qssinc.com" PhoneNumber="3457657342">
            <ns2:State>CO</ns2:State>
            <ns2:City>asfdas</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>31/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="REL14TEST0-03" FirstName="BYRON" ActiveStatus="active" LastName="BATTEASE" npn="6783452346"/>
        <AddressInfo StreetAddress="sdfsf" ZipCode="34534" EmailAddress="rkumbum@qssinc.com" PhoneNumber="3246452345">
            <ns2:State>CO</ns2:State>
            <ns2:City>asdas</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>05:55 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>06:56 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>27/05/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="REL14TEST0-08" FirstName="Bryon" ActiveStatus="active" LastName="BATTEASE" npn="3498822938"/>
        <AddressInfo StreetAddress="sdfsd" ZipCode="23422" EmailAddress="rkumbum@qssinc.com" PhoneNumber="2345673456">
            <ns2:State>CO</ns2:State>
            <ns2:City>asfasf</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>unavailable</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>14/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="SJMEYER" FirstName="fname" ActiveStatus="active" LastName="lname" npn="0000000012"/>
        <AddressInfo StreetAddress="addd" ZipCode="12312" EmailAddress="test@gmail.com" PhoneNumber="1231231231">
            <ns2:State>CO</ns2:State>
            <ns2:City>cc</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>07:00 PM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>08:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>15/04/2015</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT1" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt1" npn="0123456789"/>
        <AddressInfo StreetAddress="123 Some St" ZipCode="20171" EmailAddress="anu@us.ibm.com" PhoneNumber="7037133333">
            <ns2:State>VA</ns2:State>
            <ns2:City>Herndon</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>IBM</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT2" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt2" npn="0123456788"/>
        <AddressInfo StreetAddress="134 Some St" ZipCode="20194" EmailAddress="anu@us.ibm.com" PhoneNumber="7037420501">
            <ns2:State>VA</ns2:State>
            <ns2:City>Reston</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>available</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>ibm</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT3" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt3" npn="0123456787"/>
        <AddressInfo StreetAddress="154 Some St" ZipCode="20190" EmailAddress="anu@us.ibm.com" PhoneNumber="7037428757">
            <ns2:State>VA</ns2:State>
            <ns2:City>Ashburn</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>available</ns2:Tuesday>
                <ns2:Wednesday>available</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>cnn</ns2:AgencyName>
                <ns2:AgencyUrl>www.cnn.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="TESTDAILYRPT4" FirstName="TestDaily" ActiveStatus="active" LastName="Rpt4" npn="0123456786"/>
        <AddressInfo StreetAddress="167 Some St" ZipCode="20170" EmailAddress="anu@us.ibm.com" PhoneNumber="1234567890">
            <ns2:State>VA</ns2:State>
            <ns2:City>Herndon</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>08:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>05:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>available</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>Not Applicable</ns2:AgencyName>
                <ns2:AgencyUrl>Not Applicable</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/10/2017</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>21/07/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
    <IncrementalRecord>
        <UserInfo UserID="VCIMPL@045" FirstName="VC-IMPL" ActiveStatus="active" LastName="O'Fortyfive" npn="1234567889"/>
        <AddressInfo StreetAddress="12" ZipCode="21044" EmailAddress="vcollin@qssinc.com" PhoneNumber="4105551212">
            <ns2:State>CO</ns2:State>
            <ns2:City>Columbia</ns2:City>
        </AddressInfo>
        <PreferenceInfo>
            <ns2:WorkingHours>
                <ns2:from>
                    <ns2:Time>09:00 AM</ns2:Time>
                </ns2:from>
                <ns2:to>
                    <ns2:Time>10:00 PM</ns2:Time>
                </ns2:to>
            </ns2:WorkingHours>
            <ns2:WorkingDays>
                <ns2:Monday>available</ns2:Monday>
                <ns2:Tuesday>unavailable</ns2:Tuesday>
                <ns2:Wednesday>unavailable</ns2:Wednesday>
                <ns2:Thursday>unavailable</ns2:Thursday>
                <ns2:Friday>unavailable</ns2:Friday>
                <ns2:Saturday>unavailable</ns2:Saturday>
                <ns2:Sunday>unavailable</ns2:Sunday>
            </ns2:WorkingDays>
            <ns2:PreferredLanguage>English</ns2:PreferredLanguage>
            <ns2:PreferredContactMethod>Email address</ns2:PreferredContactMethod>
            <ns2:SearchIndicator>yes</ns2:SearchIndicator>
            <ns2:AgencyInfo>
                <ns2:AgencyName>www.ibm.com</ns2:AgencyName>
                <ns2:AgencyUrl>www.ibm.com</ns2:AgencyUrl>
            </ns2:AgencyInfo>
        </PreferenceInfo>
        <CompletionInfo>
            <shopAgreementName>SHOP Marketplace</shopAgreementName>
            <shopAgreementStatus>100</shopAgreementStatus>
            <shopAgreementExpirationDate>31/08/2016</shopAgreementExpirationDate>
            <shopAgreementAcquiredDate>02/06/2016</shopAgreementAcquiredDate>
        </CompletionInfo>
    </IncrementalRecord>
</ns3:FileDescriptionType>
