<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns3:FileDescriptionType xmlns:ns2="http://cms.cciio.mlms.gov/MLMSShopUserProfileCommonType" xmlns:ns3="http://cms.cciio.mlms.gov/MLMSShopIncrementalFileType">
    <FileIdentifier>MLMSSHOPXML20160728135000</FileIdentifier>
    <FileDateTime>2016/07/28 13:50:00</FileDateTime>
    <FileRecordCount>0</FileRecordCount>
    <FileTypeInfo FileType="WeeklyIncremental"/>
</ns3:FileDescriptionType>
